# Generated by Django 2.2.8 on 2020-06-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200614_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
